version: "3.7"
services:
  web:
    container_name: apache-php
    build: .
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
      MYSQL_ROOT_PASSWORD: toor

      # THESE NEED TO MATCH THE VALUES IN settings.php
      MYSQL_USER: "todouser"
      MYSQL_PASSWORD: "chang3 m3"
      MYSQL_DATABASE: "todo"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mariadb
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: toor

volumes:
  mariadb:
